## Solving system of linear equations

In [7]:
import numpy as np
A = np.array([
        [4, -3, 1],
        [2, 1, 3],
        [-1, 2, -5]
    ], dtype=np.dtype(float))

b = np.array([-10, 0, 17], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Array b:
[-10.   0.  17.]


In [8]:
x = np.linalg.solve(A,b)
print(x)

[ 1.  4. -2.]


## Determinant of a matrix

In [9]:
d = np.linalg.det(A)
print(d)

-60.000000000000036


## Inverse of a matrix

In [6]:
import numpy as np
A = np.array([
        [1, 2, 3],
        [0, 1, 4],
        [5, 6, 0]
    ], dtype=np.dtype(int))

A_inv = np.linalg.inv(A)
print(A_inv)

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
