## Numpy array operations

# basic operations

In [ ]:
import numpy as np

arr = np.array([10,20,30,40,50])

print(np.sum(arr))
print(np.mean())
print(np.min())
print(np.max())
print(np.std())
print(np.var())

# Slicing

In [8]:
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)

print("basic slicing " , arr[3:7])
print("slicing with steps " , arr[3:7:2])
print("negative indexing" , arr[-3])

[0 1 2 3 4 5 6 7 8 9]
basic slicing  [3 4 5 6]
slicing with steps  [3 5]
negative indexing 7


# Indexing

In [9]:
import numpy as np
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

print("specific element " ,arr_2d[1,2])
print("entire row " ,arr_2d[1])
print("entire column" ,arr_2d[:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
specific element  6
entire row  [4 5 6]
entire column [2 5 8]


## Sorting

In [13]:
unsorted = np.array([3,2,7,6,9,1])
print("sorted array" , np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],
                            [1,2],
                            [2,3]])
print("sorting 2D array by column " , np.sort(arr_2d_unsorted, axis = 0))

sorted array [1 2 3 6 7 9]
sorting 2D array by column  [[1 1]
 [2 2]
 [3 3]]


## Filter

In [17]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("even numbers " ,even_numbers)

even numbers  [ 2  4  6  8 10]


## filter with mask

In [18]:
mask = numbers > 5
print("numbers greater than 5" , numbers[mask])

numbers greater than 5 [ 6  7  8  9 10]


## fancy indexing vs np.where()

In [2]:
import numpy as np
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
indices = [0,3,5]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("np where" , numbers[where_result])

[1 4 6]
(array([5, 6, 7, 8, 9]),)
np where [ 6  7  8  9 10]


In [9]:
condition_arr = np.where(numbers > 5, numbers*2 , numbers)
print(condition_arr)                                        ## if(numbers > 5){
                                                            ##      numbers*2
                                                            ##  }else{
                                                            ##      numbers
                                                            ##  }


[ 1  2  3  4  5 12 14 16 18 20]


condition_arr = np.where(numbers > 5, "true" , "false")
print(condition_arr)

## Adding and removing data

In [2]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

new_arr = np.insert(arr1, 2, 5)
print(new_arr)

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 5 3]
[1 2 3 4 5 6]


## array compatibility

In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6,])
c = np.array([7,8,9])
print("Compatibility shapes" , a.shape == b.shape)

Compatibility shapes True


## adding rows and column

In [20]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[5],[7]])
with_new_col = np.hstack((original,new_col))
print("with new col" , with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
with new col [[1 2 5]
 [3 4 7]]


## deletion

In [3]:
arr = np.array([1,2,3,4,5,6,7])
deleted = np.delete(arr,2)
print("array after deletion" ,deleted)

array after deletion [1 2 4 5 6 7]


## spliting

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(np.split(arr,2))

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]
