## numpy array and basics

In [2]:
import numpy as np

## creating array from list

In [2]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

[1 2 3 4 5]


In [3]:
arr_2d = np.array([[1,2,3],[4,6,7]])
print("2D array" , arr_2d)

2D array [[1 2 3]
 [4 6 7]]


 ## list vs numpy array

In [5]:
py_list = [1,3,4]
print("python list multiplication" , py_list * 2)

np_arr = np.array([1,2,3]) # element wise multiplication
print("python array multiplication" , np_arr * 2)

python list multiplication [1, 3, 4, 1, 3, 4]
python array multiplication [2 4 6]


In [6]:
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n list operation time" ,time.time() - start)

start = time.time()
np_arr = np.arange(1000000) * 2
print("\n array operation time" ,time.time() - start)


 list operation time 0.2053513526916504

 array operation time 0.017186403274536133


## creating arrays from scratch

In [19]:
zeros = np.zeros((3,4))
print("zeros \n", zeros)

ones = np.ones((4,3))
print("ones \n" , ones)

full = np.full((2,2) , 5)
print("full \n", full)

random = np.random.random((2,3))
print("random \n", random)

sequence = np.arange(0,10,2)
print(sequence)

zeros 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
full 
 [[5 5]
 [5 5]]
random 
 [[0.70346497 0.44916828 0.40940978]
 [0.35509181 0.28817796 0.07820967]]
[0 2 4 6 8]


## array properties

In [21]:
arr = np.array([[1,2,3],[4,5,6]])
print("shape" , arr.shape)
print("size" , arr.size)
print("Dtype" , arr.dtype)
print("Dimension" , arr.ndim)

shape (2, 3)
size 6
Dtype int64
Dimension 2


## reshaped array

In [2]:
import numpy as np
arr = np.arange(12)
print(arr)

reshaped = arr.reshape((3,4))
print(reshaped)

flattened = reshaped.flatten()
print(flattened)

# returned view , instead of copy
raveled = reshaped.ravel()
print(raveled)

transpose = reshaped.T
print(transpose)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## reversing an array

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print(reversed_arr)

[8 7 6 5 4 3 2 1]


In [6]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
